Fix capabilities concatenation in xattr
By accident arrays of capabilities were added insteads of strings.

Fixes errors like

```
ERROR: /usr/local/google/home/rmohr/gerrit/kubevirt/cmd/virt-launcher/BUILD.bazel:73:7: in _xattrs rule //cmd/virt-launcher:blub:
Traceback (most recent call last):
	File "/usr/local/google/home/rmohr/.cache/bazel/_bazel_rmohr/4c1501bf8a3fa32b59ed554fc2f4f732/external/bazeldnf/internal/xattrs.bzl", line 28, column 44, in _xattrs_impl
		args += ["--capabilities", ",".join(capabilities)]
Error in join: expected string for sequence element 0, got 'list'
```

Signed-off-by: Roman Mohr <rmohr@google.com>